config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about'

  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :user_id, presence: true, uniqueness: {scope: :book_id}
  validates :book_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  
  validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  

  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    flash[:notice] = "successfully"
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "successfully"
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
  
  private
  
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id]).destroy
    redirect_to request.referer
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :move_to_books, only: [:edit, :update]

  def index
    @book = Book.new
    @books = Book.all
    @user = User.find(current_user.id)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @book2 = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def move_to_books
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :move_to_user, only: [:edit, :update]
  
  def index
    @user = User.find(current_user.id)
    @users = User.all
    @book = Book.new
  end
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.reverse_order
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def move_to_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_sidebar.html.erb
  
    <div class="p-3">
       <h1>User info</h1>
       <table class="table">
        <thead>
          <tr>
            <th>
              <%= link_to user_path(user.id) do %>
                <%= attachment_image_tag user, :profile_image, :fill,100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
              <% end %>
            </th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>name</td>
            <td><%= user.name %></td>
          </tr>
          <tr>
            <td>introduction</td>
            <td><%= user.introduction %></td>
          </tr>
        </tbody>
      </table>

       <span>
          <%= link_to edit_user_path(user.id) do%>
           <span class="btn btn-primary w-100">
             <i class="fas fa-user-cog"></i>
           </span>
         <% end %>
       </span>
    </div>
    <div class="p-3">
      <h1>New book</h1>
      <%= form_with model: book, local:true do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %><br>
        <%= f.submit 'Create Book', class:"btn btn-success" %>
      <% end %>
    </div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div class="error-message">
      <p class="error-amount"><%= @book.errors.count %> error prohibited this book from being saved:</p>
      <ul class="list">
            <% @book.errors.full_messages.each do |message| %>
              <li class="list-error"><%= message %></li>
            <% end %>
      </ul>
  </div>
<% end %>
<div class="main">
  <div class="edit">
    <h1>Editing Book</h1>
    <div>
      <%= form_with model:@book, locla:true do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p>opinion</p>
        <%= f.text_area :body %><br>
        <%= f.submit "Update Book", method: :patch %>
      <% end %>
      <div class="SB">
        <span class="m-1"><%= link_to "Show", book_path(@book.id) %></span>
        <div class="m-1"> | </div>
        <span class="m-1"><%= link_to "Back", books_path %></span>
      </div>

    </div>
  </div>


</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div class="error-message">
      <p class="error-amount"><%= @book.errors.count %> error prohibited this book from being saved:</p>
      <ul class="list">
            <% @book.errors.full_messages.each do |message| %>
              <li class="list-error"><%= message %></li>
            <% end %>
      </ul>
  </div>
<% end %> 
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/sidebar', book: @book, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Favorites</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill,100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <% if book.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class="fas fa-heart"><%= book.favorites.count %></i>
                <% end %>
              </td>
            <% else %>
              <td>
                <%= link_to book_favorites_path(book), method: :post do %>
                  <i class="far fa-heart"><%= book.favorites.count %></i>
                <% end %>
              </td>
            <% end %>
            <td>コメント数：<%= book.book_comments.count %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p class="notice"><%= flash[:notice] %></p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/sidebar', book: @book2, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image, :fill,100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                <br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
            <% if @book.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                  <i class="fas fa-heart"><%= @book.favorites.count %></i>
                <% end %>
              </td>
            <% else %>
              <td>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  <i class="far fa-heart"><%= @book.favorites.count %></i>
                <% end %>
              </td>
            <% end %>
            <td>コメント件数：<%= @book.book_comments.count %></td>
            <% if @book.user == current_user %>
              <td class="btn btn-success m-1">
                <%= link_to "Edit", edit_book_path(@book.id) %>
              </td>
              <td class="btn btn-danger m-1">
                <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "Are you sure？" %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <table class="table">
        <tbody>
          <% @book.book_comments.each do |book_comment| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
                <br>
                <%= book_comment.user.name %>
              <% end %>
            </td>
            <td><%= book_comment.comment %></td>
            <td><%= book_comment.created_at.strftime('%Y/%m/%d') %></td>
            <% if book_comment.user == current_user %>
              <td class="btn btn-danger m-1">
                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete ,"data-confirm" => "Are you sure？" %>
              </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div>
        <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
          <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
          <%= f.submit "送信する" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="main">
  <h1>welcome to <i class="fas fa-book">Bookers</i></h1>
</div>

app/views/homes/top.html.erb
<p class="notice"><%= flash[:notice] %></p>
<div class="main">
  <div class="top">
    <h1>welcome to <i class="fas fa-book">Bookers</i></h1>
    <p>
      In <i class="fas fa-book">Bookers</i>,<br>
      you can share and exchange your opinions , inpressions , and emotions<br>
      about various books!
    </p>
    <span>
      <span class="btn btn-info w-100 m-1"><%= link_to "Log in", new_user_session_path %></span>
      <br>
      <span class="btn btn-success w-100 m-1"><%= link_to "Sign up", new_user_registration_path %></span>
    </span>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/12ff2199f9.js" crossorigin="anonymous"></script>

    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <h2 class="text-light"><%= link_to "Bookers", root_path %></h2>
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="p-2 list-item">
              <%= link_to user_path(current_user.id) do %>
                <i class="fas fa-home text-light">Home</i>
              <% end %>
            </li>
            <li class="p-2 list-item">
              <%= link_to users_path do %>
                <i class="fas fa-users text-light">Users</i>
              <% end %>
            </li>
            <li class="p-2 list-item">
              <%= link_to books_path do %>
                <i class="fas fa-book-open text-light">Books</i>
              <% end %>
            </li>
            <li class="p-2 list-item">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt text-light">logout</i>
              <% end %>
            </li>
          <% else %>
            <li class="p-2 list-item">
              <%= link_to root_path do %>
                <i class="fas fa-home text-light">Home</i>
              <% end %>
            </li>
            <li class="p-2 list-item">
              <%= link_to '/home/about' do %>
                <i class="fas fa-link text-light">About</i>
              <% end %>
            </li>
            <li class="p-2 list-item">
              <%= link_to new_user_registration_path do %>
                <i class="fas fa-user-plus text-light">sign up</i>
              <% end %>
            </li>
            <li class="p-2 list-item">
              <%= link_to new_user_session_path do %>
                <i class="fas fa-sign-in-alt text-light">login</i>
              <% end %>
            </li>
          <% end %>
        </ul>
      </nav>
    </header>


      <%= yield %>




    <footer>CopyRight Infratop.inc</footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="error-message">
      <p class="error-amount"><%= @user.errors.count %> error prohibited this book from being saved:</p>
      <ul class="list">
            <% @user.errors.full_messages.each do |message| %>
              <li class="list-error"><%= message %></li>
            <% end %>
      </ul>
  </div>
<% end %> 
<div class="main">
  <div class="edit">
    <h1>User info</h1>
    <div>
      <%= form_with model:@user, locla:true do |f| %>
        <p>name</p>
        <%= f.text_field :name %>
        <p>image</p>
        <%= f.attachment_field :profile_image %>
        <p>introduction</p>
        <%= f.text_area :introduction %><br>
        <%= f.submit "Update User" %>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/sidebar', book: @book, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Users</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill,100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
            </td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<p class="notice"><%= flash[:notice] %></p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/sidebar', book: @book, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table">
        <thead>
          <tr>
            <th>
                <% if @user.id =! current_user.id %>
                <% end %>
            </th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Favorites</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
                <% if @user.id =! current_user.id %>
                  <%= link_to user_path(@user.id) do %>
                    <%= attachment_image_tag @user, :profile_image, :fill,100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                  <% end %>
                <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <% if book.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class="fas fa-heart"><%= book.favorites.count %></i>
                <% end %>
              </td>
            <% else %>
              <td>
                <%= link_to book_favorites_path(book), method: :post do %>
                  <i class="far fa-heart"><%= book.favorites.count %></i>
                <% end %>
              </td>
            <% end %>
            <td>コメント件数：<%= book.book_comments.count %></td>
            <% if book.user == current_user %>
              <td class="btn btn-success m-1">
                <%= link_to "Edit", edit_book_path(book.id) %>
              </td>
              <td class="btn btn-danger m-1">
                <%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure？" %>
              </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
   
  </div>

</div>